(()=>{'use strict';
const tr=s=>window.KrishiI18n?.t(s)||s,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>window.KrishiI18n?.getLanguage()||'en';
const fieldData=()=>{try{if(typeof demo!=='undefined'&&demo)return demoData;return KrishiWorkflow.read()}catch{return {observations:[],actions:[]}}};
function data(c){const d=fieldData();const related=c?d.actions.filter(a=>a.id===c.sentinelActionId):d.actions;const observed=c?d.observations.filter(o=>related.some(a=>a.observationId===o.id)):d.observations;return {demo:typeof demo!=='undefined'&&demo,generatedAt:Date.now(),farmer:typeof state!=='undefined'?state.user:null,scans:c?[]:typeof getScans==='function'?getScans():[],cases:c?[c]:typeof getCases==='function'?getCases():[],observations:observed,actions:related};}
function report(c){if(typeof toast==='function')toast(tr('Generating PDF report…'));KrishiReports.openPDF(data(c),lang());}
const bar=document.createElement('div');bar.className='report-toolbar';bar.innerHTML=`<button type="button" class="btn btn-primary pdf-report-btn" id="full-report">📄 <span>${tr('Generate PDF report')}</span></button>`;
(document.querySelector('main')||document.querySelector('.shell')).append(bar);bar.querySelector('#full-report').onclick=()=>report();
// Capture legacy export controls so all report entry points use the selected language.
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(['export','exportLearning','downloadLatestReport'].includes(b.id)){e.preventDefault();e.stopImmediatePropagation();report();}if(b.dataset.download&&typeof window.KrishiWorkflow!=='undefined'){e.preventDefault();e.stopImmediatePropagation();report();}},true);
if(typeof state==='undefined'||!document.querySelector('#caseDetail'))return;
downloadReport=report;exportLearning=()=>KrishiReports.download(KrishiReports.csv(data(),lang()),`KrishiRakshak-${lang()}.csv`,'text/csv;charset=utf-8');
const oldDashboard=renderDashboard;renderDashboard=function(){oldDashboard();const cases=getCases(),d=fieldData(),open=cases.filter(c=>c.status!=='Reviewed');document.querySelector('#healthScore').textContent=open.length;document.querySelector('#healthScore').parentElement.querySelector('span').textContent=tr('Awaiting expert review');document.querySelector('#healthText').textContent=tr('Review pending cases before choosing a treatment.');let panel=document.querySelector('#next-actions');if(!panel){panel=document.createElement('section');panel.id='next-actions';panel.className='card';document.querySelector('#dashboardPage .section-wrap').prepend(panel);}const overdue=d.actions.filter(a=>a.status!=='Closed'&&a.due<Date.now());panel.innerHTML=`<h3>${tr('Your next steps')}</h3><div class="next-grid"><div><strong>${d.observations.length}</strong><span>${tr('Field observations')}</span></div><div><strong>${overdue.length}</strong><span>${tr('Overdue follow-ups')}</span></div><div><strong>${cases.filter(c=>c.status==='Reviewed').length}</strong><span>${tr('Reviewed cases')}</span></div></div><p>${open.length?tr('An expert review is pending. Open your case to add field details or download a referral.'):tr('No pending reviews. Record new symptoms or revisit your marked plants.')}</p><button class="btn btn-light" data-next="scan">${tr('Scan a leaf')}</button> <button class="btn btn-light" data-next="expert">${tr('Open expert records')}</button> <a class="btn btn-light" href="index.html">${tr('Open Field Sentinel')}</a>`;panel.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>showPage(b.dataset.next));};
renderCaseDetail=function(id){const c=getCases().find(x=>x.id===id);if(!c)return;const q=s=>document.querySelector(s);q('#caseDetail').innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:8px"><p class="eyebrow" style="margin:0">${esc(c.id)} · ${tr(c.status)}</p><button class="btn btn-light danger-btn" id="deleteCaseTop" type="button" style="padding:6px 14px;font-size:12px;font-weight:600">🗑 ${tr('Delete case')}</button></div><h2>${esc(c.crop)} · ${esc(c.disease)}</h2><p>${esc(c.farmer)} · ${esc(c.location)}</p><p class="context-box">${tr('This is a local review record. Download it to share with your expert; no message has been sent.')}</p>${/^data:image\/(jpeg|png|webp);base64,/.test(c.image||'')?`<img class="case-image" src="${esc(c.image)}" alt="${tr('Crop photo')}">`:''}<p>${esc(c.problem||tr('No confirmed diagnosis.'))}</p><form id="review-form"><label class="field"><span>${tr('Farmer observations')}</span><textarea id="farmer-notes" maxlength="2000">${esc(c.farmerNotes||'')}</textarea></label><label class="field"><span>${tr('Reviewer / laboratory name')}</span><input id="reviewer-name" maxlength="100" value="${esc(c.reviewer||'')}"></label><label class="field"><span>${tr('Expert recommendation')}</span><textarea id="expertResponse" maxlength="3000">${esc(c.response||'')}</textarea></label><label class="field"><span>${tr('Next visit date')}</span><input id="follow-up" type="date" value="${esc(c.followUp||'')}"></label><div class="case-actions"><button class="btn btn-primary" type="submit">${tr('Save review notes')}</button><button class="btn btn-light" id="reportExpert" type="button">${tr('Download detailed report')}</button><button class="btn btn-light" id="closeCase" type="button">${tr('Mark reviewed')}</button><button class="btn btn-light danger-btn" id="deleteCase" type="button">🗑 ${tr('Delete case')}</button></div><p id="review-feedback" role="status"></p></form>`;
const remove=()=>{if(!confirm(tr('Delete this case from the queue? This cannot be undone.')))return;const remaining=getCases().filter(x=>x.id!==id);saveCases(remaining);state.currentCaseId=remaining[0]?.id||null;renderCases();if(typeof renderDashboard==='function')renderDashboard();toast(tr('Case removed from queue.'));};q('#deleteCase')?.addEventListener('click',remove);q('#deleteCaseTop')?.addEventListener('click',remove);
const save=(close=false)=>{const reviewer=q('#reviewer-name').value.trim(),response=q('#expertResponse').value.trim();if(close&&(!reviewer||!response)){q('#review-feedback').textContent=tr('Add the reviewer name and recommendation before marking reviewed.');return false;}saveCases(getCases().map(x=>x.id===id?{...x,reviewer,response,farmerNotes:q('#farmer-notes').value.trim(),followUp:q('#follow-up').value,status:close?'Reviewed':response?'Responded':'Pending',reviewedAt:close?Date.now():x.reviewedAt}:x));return true;};q('#review-form').onsubmit=e=>{e.preventDefault();save();renderCases();toast(tr('Review notes saved on this device.'));};q('#closeCase').onclick=()=>{if(save(true)){renderCases();renderDashboard();}};q('#reportExpert').onclick=()=>{save();report(getCases().find(x=>x.id===id));};};
const oldCases=renderCases;renderCases=function(){oldCases();if(!getCases().length){document.querySelector('#caseDetail').innerHTML=`<div class="empty-case-guide"><div class="guide-icon">🌱</div><h3>${tr('Start a review request')}</h3><p class="guide-desc">${tr('Add a leaf photo and describe what changed. A report helps your expert review the case.')}</p><button class="btn btn-primary" id="expert-start" type="button">${tr('Scan a leaf')}</button><div class="guide-steps"><div class="guide-step"><span>1</span><b>${tr('Take leaf photo')}</b><small>${tr('Clear photo in daylight')}</small></div><div class="guide-step"><span>2</span><b>${tr('AI triage')}</b><small>${tr('Instant crop risk check')}</small></div><div class="guide-step"><span>3</span><b>${tr('Expert review')}</b><small>${tr('Agronomist recommendations')}</small></div></div></div>`;document.querySelector('#expert-start').onclick=()=>showPage('scan');}};
document.querySelector('#expertBtn').onclick=()=>{if(!state.selectedImage&&!state.lastResult)return toast(tr('Upload a clear leaf photo first.'));createExpertCase(state.lastResult||{crop:document.querySelector('#cropSelector').value==='auto'?tr('Not recorded'):document.querySelector('#cropSelector').value,disease:tr('Awaiting expert assessment'),confidence:null,source:'Manual photo review',problem:tr('No confirmed diagnosis.')});};
window.addEventListener('krishi-language',()=>{const b=document.querySelector('#full-report span');if(b)b.textContent=tr('Generate PDF report');if(state.user)renderDashboard();if(state.currentCaseId)renderCaseDetail(state.currentCaseId);});if(state.user)renderDashboard();
})();
