(function(root){'use strict';
const rows=[
['title','Farm health and follow-up report','खेत स्वास्थ्य और अगली जाँच की रिपोर्ट','शेत आरोग्य व पुढील पाहणी अहवाल'],
['date','Generated on','तैयार करने की तारीख','तयार केल्याची तारीख'],['farmer','Farmer','किसान','शेतकरी'],['location','Village / district','गाँव / जिला','गाव / जिल्हा'],['summary','Summary','सारांश','सारांश'],['scans','Leaf assessments','पत्ती के आकलन','पानांचे मूल्यांकन'],['cases','Expert review records','विशेषज्ञ समीक्षा रिकॉर्ड','तज्ज्ञ परीक्षण नोंदी'],['fields','Field observations','खेत के अवलोकन','शेत निरीक्षणे'],['actions','Actions and follow-up','कार्य और अगली जाँच','कृती व पुढील पाहणी'],['crop','Crop','फसल','पीक'],['finding','Suspected finding','संभावित समस्या','संभाव्य समस्या'],['source','Assessment source','आकलन का स्रोत','मूल्यांकन स्रोत'],['status','Review status','समीक्षा स्थिति','परीक्षण स्थिती'],['notes','Observations / notes','अवलोकन / टिप्पणियाँ','निरीक्षणे / टिपा'],['advice','Advice / next steps','सलाह / अगले कदम','सल्ला / पुढील पावले'],['reviewer','Reviewer / laboratory','समीक्षक / प्रयोगशाला','परीक्षक / प्रयोगशाळा'],['due','Next visit date','अगली जाँच की तारीख','पुढील भेटीची तारीख'],['id','Record ID','रिकॉर्ड संख्या','नोंद क्रमांक'],['field','Field','खेत','शेत'],['sampled','Plants inspected','जाँचे गए पौधे','तपासलेली झाडे'],['affected','Plants with symptoms','लक्षण वाले पौधे','लक्षणे असलेली झाडे'],['trap','Trap count','ट्रैप की संख्या','सापळ्यातील संख्या'],['stage','Crop stage','फसल अवस्था','पीक अवस्था'],['weather','Weather at observation','अवलोकन के समय मौसम','निरीक्षणावेळी हवामान'],['temperature','Temperature °C','तापमान °C','तापमान °C'],['humidity','Humidity %','आर्द्रता %','आर्द्रता %'],['rain','Rain mm','वर्षा mm','पाऊस mm'],['empty','No records available','कोई रिकॉर्ड उपलब्ध नहीं','नोंदी उपलब्ध नाहीत'],['unknown','Not recorded','दर्ज नहीं','नोंद नाही'],['pending','Pending review','समीक्षा बाकी','परीक्षण बाकी'],['print','Print / Save as PDF','प्रिंट / PDF में सेव करें','प्रिंट / PDF म्हणून जतन करा'],['download','Download detailed report','विस्तृत रिपोर्ट डाउनलोड करें','सविस्तर अहवाल डाउनलोड करा'],['csv','Download spreadsheet','स्प्रेडशीट डाउनलोड करें','स्प्रेडशीट डाउनलोड करा'],['notice','AI findings are unconfirmed. Reviews are entered on this device, not automatically sent to an expert. Consult a qualified local expert before treatment. Farmer notes and disease names are preserved as recorded.','AI के निष्कर्ष पुष्ट नहीं हैं। समीक्षा इस उपकरण पर दर्ज होती है, विशेषज्ञ को अपने आप नहीं भेजी जाती। उपचार से पहले स्थानीय विशेषज्ञ की सलाह लें। किसान की टिप्पणियाँ और रोगों के नाम मूल रूप में रखे गए हैं।','AI निष्कर्ष निश्चित नाहीत. परीक्षण या उपकरणावर नोंदवले जाते; तज्ज्ञांकडे आपोआप पाठवले जात नाही. उपचारापूर्वी स्थानिक तज्ज्ञांचा सल्ला घ्या. शेतकऱ्यांच्या टिपा व रोगांची नावे मूळ स्वरूपात ठेवली आहेत.']];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function labels(lang){const n={en:1,hi:2,mr:3}[lang]||1;return Object.fromEntries(rows.map(r=>[r[0],r[n]]));}
function build(data,lang='en'){lang=['en','hi','mr'].includes(lang)?lang:'en';const l=labels(lang),locale={en:'en-IN',hi:'hi-IN',mr:'mr-IN'}[lang];const date=v=>v&&Number.isFinite(new Date(v).getTime())?new Date(v).toLocaleString(locale):l.unknown;
const display=v=>v===null||v===undefined||v===''?l.unknown:String(v);
const field=(key,v)=>`<div class="row"><dt>${escape(l[key]||key)}</dt><dd>${escape(display(v))}</dd></div>`;
const weather=w=>w?`<h4>${l.weather}</h4><dl>${field('temperature',w.temperature_2m)}${field('humidity',w.relative_humidity_2m)}${field('rain',w.precipitation)}</dl>`:'';
const totalItems=(data.scans?.length||0)+(data.cases?.length||0)+(data.observations?.length||0)+(data.actions?.length||0);
const section=(key,items,fn)=>{if(!items||!items.length){return totalItems===0?`<section><p>${l.empty}</p></section>`:'';}return `<section><h2>${l[key]} (${items.length})</h2>${items.map(fn).join('')}</section>`;};
const image=src=>typeof src==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(src)?`<img alt="${l.scans}" src="${src}">`:'';
return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KrishiRakshak — ${l.title}</title><style>
@page{size:A4;margin:12mm 15mm}
body{font-family:system-ui,-apple-system,"Noto Sans Devanagari",sans-serif;background:#f7f0e5;color:#493526;max-width:920px;margin:auto;padding:24px;line-height:1.6;-webkit-print-color-adjust:exact;print-color-adjust:exact}
h1,h2,h3{color:#5c412d;margin-top:0}
section,article{border:1px solid #d8c6af;border-radius:12px;padding:18px;margin:16px 0;background:#fffaf3}
article{break-inside:avoid;page-break-inside:avoid}
dl{margin:0}
.row{display:grid;grid-template-columns:35% 65%;border-bottom:1px solid #e7dac8;padding:7px 0}
.row:last-child{border-bottom:0}
dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}
dt{font-weight:600;color:#6b4f3a}
img{max-width:260px;max-height:190px;border-radius:8px;border:1px solid #dfd2c1;margin:8px 0}
.no-print{display:flex;justify-content:space-between;align-items:center;background:#fffaf2;border:1px solid #dfd2c1;border-radius:12px;padding:12px 18px;margin-bottom:20px;box-shadow:0 2px 10px rgba(67,48,30,0.06)}
.btn-print{background:#5c412d;color:#fffaf3;padding:10px 20px;border:0;border-radius:8px;font-weight:700;font-size:14px;cursor:pointer;display:inline-flex;align-items:center;gap:8px}
.btn-print:hover{background:#443022}
.btn-close{background:#eee0cb;color:#5c412d;padding:10px 16px;border:0;border-radius:8px;font-weight:700;font-size:13px;cursor:pointer}
.btn-close:hover{background:#dfceb7}
.notice{font-size:12.5px;background:#eee0cb;padding:12px 16px;border-radius:8px;line-height:1.5;color:#5c412d}
@media print{body{padding:0;background:white!important}button,.no-print{display:none!important}section{border:1px solid #eee!important;padding:12px!important}h2,h3{break-after:avoid}}
</style><script>
window.addEventListener('DOMContentLoaded',function(){setTimeout(function(){try{window.print()}catch(e){}},350);});
</script></head><body>
<div class="no-print"><div style="font-weight:700;color:#5c412d">🌱 KrishiRakshak — ${l.title}</div><div><button type="button" class="btn-print" onclick="window.print()">🖨️ ${l.print}</button> <button type="button" class="btn-close" onclick="window.close()">✕</button></div></div>
<h1>KrishiRakshak</h1>${data.demo?'<p class="notice">'+({en:'Demonstration data — not real field records',hi:'डेमो डेटा — असली खेत रिकॉर्ड नहीं',mr:'डेमो डेटा — खऱ्या शेत नोंदी नाहीत'}[lang])+'</p>':''}<h2>${l.title}</h2><p>${l.date}: ${date(data.generatedAt||Date.now())}</p><dl>${field('farmer',data.farmer?.name)}${field('location',data.farmer?.location)}</dl><p class="notice">${l.notice}</p>
${section('scans',data.scans||[],s=>`<article><h3>${escape(s.crop||l.unknown)} · ${escape(s.disease||l.unknown)}</h3>${image(s.image)}<dl>${field('id',s.id)}${field('date',date(s.timestamp))}${field('source',s.source)}${field('notes',s.problem)}${field('advice',s.action)}${field('status',s.agreement||l.pending)}</dl>${weather(s.weather)}</article>`)}
${section('cases',data.cases||[],c=>`<article><h3>${escape(c.id)}</h3>${image(c.image)}<dl>${field('farmer',c.farmer)}${field('location',c.location)}${field('crop',c.crop)}${field('finding',c.disease)}${field('date',date(c.createdAt))}${field('notes',c.farmerNotes||c.problem)}${field('source',c.source)}${field('status',root.KrishiI18n?.t(c.status,lang)||c.status)}${field('reviewer',c.reviewer)}${field('advice',c.response)}${field('due',c.followUp)}</dl>${weather(c.weather)}</article>`)}
${section('fields',data.observations||[],o=>`<article><h3>${escape(o.field)}</h3><dl>${field('id',o.id)}${field('location',o.village)}${field('crop',o.crop)}${field('stage',root.KrishiI18n?.t(o.stage,lang)||o.stage)}${field('date',date(o.at))}${field('sampled',o.sampled)}${field('affected',o.affected)}${field('trap',o.trap)}${field('notes',o.notes)}</dl></article>`)}
${section('actions',data.actions||[],a=>`<article><dl>${field('id',a.id)}${field('status',root.KrishiI18n?.t(a.status,lang)||a.status)}${field('due',date(a.due))}${field('reviewer',a.reviewer)}${field('advice',a.review)}</dl></article>`)}<p style="font-size:12px;color:#7a6656;margin-top:24px">KrishiRakshak · ${l.title}</p></body></html>`;
}
function csv(data,lang){const l=labels(lang);const lines=[[l.id,l.crop,l.finding,l.source,l.status,l.notes,l.advice,l.date]];for(const s of data.scans||[])lines.push([s.id,s.crop,s.disease,s.source,s.agreement||l.pending,s.problem,s.action,s.timestamp?new Date(s.timestamp).toISOString():'']);for(const c of data.cases||[])lines.push([c.id,c.crop,c.disease,c.source,c.status,c.farmerNotes||c.problem,c.response,c.createdAt?new Date(c.createdAt).toISOString():'']);for(const o of data.observations||[])lines.push([o.id,o.crop,'',l.fields,'',`${l.field}: ${o.field}; ${l.sampled}: ${o.sampled}; ${l.affected}: ${o.affected}; ${o.notes||''}`,'',o.at?new Date(o.at).toISOString():'']);return '\ufeff'+lines.map(row=>row.map(v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.style.display='none';a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{if(a.parentNode)a.parentNode.removeChild(a);URL.revokeObjectURL(u);},1500);}
function openPDF(data,lang='en'){lang=['en','hi','mr'].includes(lang)?lang:'en';const html=build(data,lang);const blob=new Blob([html],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const win=window.open(url,'_blank');if(!win||win.closed||typeof win.closed==='undefined'){let frame=document.getElementById('krishi-pdf-frame');if(!frame){frame=document.createElement('iframe');frame.id='krishi-pdf-frame';frame.style.position='fixed';frame.style.right='0';frame.style.bottom='0';frame.style.width='0';frame.style.height='0';frame.style.border='0';frame.style.opacity='0';document.body.appendChild(frame);}frame.src=url;frame.onload=()=>{setTimeout(()=>{try{frame.contentWindow.focus();frame.contentWindow.print();}catch(e){download(html,`KrishiRakshak-${data.cases?.[0]?.id||'Report'}-${lang}.html`,'text/html;charset=utf-8');}},350);};}}
root.KrishiReports={labels,build,csv,download,openPDF};if(typeof module!=='undefined')module.exports=root.KrishiReports;
})(typeof window==='undefined'?globalThis:window);
