/* Field context shared by the image workspace and action board. */
(function(){
'use strict';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=new URLSearchParams(location.search).get('field')||'';
const container=document.createElement('div');container.className='field-link-banner';
document.querySelector('#scanPage .section-wrap').prepend(container);
function fields(){try{return KrishiWorkflow.read().observations.filter((o,i,a)=>a.findIndex(x=>x.fieldId===o.fieldId)===i)}catch{return []}}
function renderContext(){const list=fields();container.innerHTML=`<div class="field-link-header"><div class="field-link-title-group"><span class="field-link-badge">🌾 Field Sync</span><b>Connect this photo to your field</b><p>Choose a field to keep scans, observations and follow-up together.</p></div></div><div class="field-link-controls"><div class="field-link-select-group"><select id="linked-field" aria-label="Linked field"><option value="">Choose a saved field</option>${list.map(o=>`<option value="${escape(o.fieldId)}" ${selected===o.fieldId?'selected':''}>${escape(o.field)} · ${escape(o.crop)}</option>`).join('')}</select></div><div class="field-link-btn-group"><a href="index.html" class="field-link-action-btn"><span>↗ Open Field Sentinel</span></a><button id="save-photo-review" type="button" class="field-link-action-btn save-manual"><span>Save photo for review without AI</span></button></div></div><p id="link-status" class="field-link-status" hidden></p><div class="field-link-footer"><p class="mini">If the image model is unavailable, the photo can still be recorded and reviewed. No diagnosis is fabricated.</p></div>`;container.querySelector('select').onchange=e=>selected=e.target.value;container.querySelector('#save-photo-review').onclick=manual;}
async function manual(){if(!selected)return toast('Choose a saved field first.');if(!state.selectedImage)return toast('Upload a clear leaf photo first.');try{const d=KrishiWorkflow.read(),o=d.observations.find(x=>x.fieldId===selected);if(!o)throw Error('Choose a saved field first.');const img=await photo(state.selectedImage);const scan={id:crypto.randomUUID(),at:Date.now(),disease:'Awaiting expert assessment',source:'Photo observation — no AI diagnosis',confidence:null};const linked=KrishiWorkflow.linkScan(d,selected,scan);linked.photo=img;KrishiWorkflow.plan(d,linked);KrishiWorkflow.write(d);container.querySelector('#link-status').textContent='Photo saved. Review and follow-up are ready in Field Sentinel.';toast('Photo saved to your field action plan.');}catch(e){toast(e.message)}}
async function photo(file){if(file.size>12*1024*1024)throw Error('Photo must be smaller than 12 MB.');const url=URL.createObjectURL(file);try{const img=await new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=url});const c=document.createElement('canvas'),k=Math.min(1,900/Math.max(img.width,img.height));c.width=img.width*k;c.height=img.height*k;c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.68);}finally{URL.revokeObjectURL(url)}}
const originalSave=saveScan;saveScan=function(result,onnx){originalSave(result,onnx);if(!selected)return;try{const d=KrishiWorkflow.read();KrishiWorkflow.linkScan(d,selected,{id:state.lastScan.id,at:Date.now(),disease:String(result.disease||'Uncertain condition'),source:String(result.source||'Image assessment'),confidence:result.confidence});KrishiWorkflow.write(d);container.querySelector('#link-status').textContent='Scan linked to this field.';}catch(e){toast('Scan saved, but field linking failed.')}};
const originalCase=createExpertCase;createExpertCase=function(result){originalCase(result);if(!selected)return;try{const d=KrishiWorkflow.read(),o=d.observations.filter(x=>x.fieldId===selected).sort((a,b)=>b.at-a.at)[0];if(!o)return;const a=KrishiWorkflow.plan(d,o);const cases=getCases();cases[0].sentinelActionId=a.id;saveCases(cases);KrishiWorkflow.write(d);}catch{toast('Expert case saved; field action link could not be saved.')}};
const originalCases=saveCases;saveCases=function(cases){originalCases(cases);try{const d=KrishiWorkflow.read();let changed=false;for(const c of cases){const a=d.actions.find(a=>a.id===c.sentinelActionId);if(a&&c.response&&a.review!==c.response){a.review=c.response;if(a.status!=='Closed')a.status='Reviewed';d.audit.push({at:Date.now(),text:'Local expert response linked to '+a.id});changed=true;}}if(changed)KrishiWorkflow.write(d);}catch{toast('Field review could not be synchronised.')}};
const originalGetCases=getCases;getCases=function(){const cases=originalGetCases();try{const d=KrishiWorkflow.read();return cases.map(c=>{const a=d.actions.find(a=>a.id===c.sentinelActionId);return a?.review?{...c,response:a.review,status:c.status==="Reviewed"?"Reviewed":"Responded"}:c;});}catch{return cases;}};
renderContext();
// An explicit local-workspace entry avoids pretending a browser password is secure authentication.
const entry=document.createElement('button');entry.className='btn btn-light full';entry.textContent='Continue in local workspace';entry.onclick=()=>{enterApp({id:'field-workspace',name:'Farmer',location:'',crop:''});showPage('scan');};document.querySelector('.auth-card').append(entry);
document.addEventListener('DOMContentLoaded',()=>{if(state.user&&new URLSearchParams(location.search).get('page')==='scan')showPage('scan');});
})();
